stages:
  - build
  - test

variables:
  PYTHON_VERSION: "3.11"

build:
  stage: build
  image: python:${PYTHON_VERSION}
  script:
    - python -m pip install --upgrade pip
    - pip install pytest
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .
    expire_in: 1 hour

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - pip install pytest
    - pytest
